package postgres

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/paolaU7/AAM/backend/internal/domain"
)

// ── entry_points ─────────────────────────────────────────────────────────────

type EntryPointRepo struct{ pool *pgxpool.Pool }

func NewEntryPointRepo(pool *pgxpool.Pool) *EntryPointRepo { return &EntryPointRepo{pool} }

func scanEntryPoint(row pgx.Row) (domain.EntryPoint, error) {
	var e domain.EntryPoint
	err := row.Scan(&e.ID, &e.Name, &e.Location, &e.CreatedAt)
	return e, err
}

func (r *EntryPointRepo) GetAll(ctx context.Context) ([]domain.EntryPoint, error) {
	rows, err := r.pool.Query(ctx,
		`SELECT id, name, location, created_at FROM entry_points ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []domain.EntryPoint
	for rows.Next() {
		e, err := scanEntryPoint(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

func (r *EntryPointRepo) getByID(ctx context.Context, id string) (*domain.EntryPoint, error) {
	e, err := scanEntryPoint(r.pool.QueryRow(ctx,
		`SELECT id, name, location, created_at FROM entry_points WHERE id = $1`, id))
	if noRows(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}

func (r *EntryPointRepo) Create(ctx context.Context, name string, location *string) (domain.EntryPoint, error) {
	e, err := scanEntryPoint(r.pool.QueryRow(ctx,
		`INSERT INTO entry_points (name, location) VALUES ($1, $2)
		 RETURNING id, name, location, created_at`,
		name, derefStr(location)))
	if err != nil {
		return domain.EntryPoint{}, mapDBError(err, "No se pudo crear el punto de acceso.")
	}
	return e, nil
}

func (r *EntryPointRepo) Update(ctx context.Context, id, name string, location *string) (*domain.EntryPoint, error) {
	tag, err := r.pool.Exec(ctx,
		`UPDATE entry_points SET name = $2, location = $3 WHERE id = $1`,
		id, name, derefStr(location))
	if err != nil {
		return nil, mapDBError(err, "No se pudo actualizar el punto de acceso.")
	}
	if tag.RowsAffected() == 0 {
		return nil, nil
	}
	return r.getByID(ctx, id)
}

func (r *EntryPointRepo) Delete(ctx context.Context, id string) (bool, error) {
	tag, err := r.pool.Exec(ctx, `DELETE FROM entry_points WHERE id = $1`, id)
	if err != nil {
		return false, mapDBError(err, "No se pudo eliminar el punto de acceso.")
	}
	return tag.RowsAffected() > 0, nil
}

// ── devices (admin registry) ─────────────────────────────────────────────────

type DeviceConfigRepo struct{ pool *pgxpool.Pool }

func NewDeviceConfigRepo(pool *pgxpool.Pool) *DeviceConfigRepo { return &DeviceConfigRepo{pool} }

const deviceConfigSelect = `
	SELECT d.id, d.entry_point_id, ep.name, d.name, d.is_active, d.created_at, d.revoked_at
	FROM devices d
	JOIN entry_points ep ON ep.id = d.entry_point_id`

func scanDeviceConfig(row pgx.Row) (domain.DeviceConfig, error) {
	var d domain.DeviceConfig
	err := row.Scan(&d.ID, &d.EntryPointID, &d.EntryPointName, &d.Name, &d.IsActive, &d.CreatedAt, &d.RevokedAt)
	return d, err
}

func (r *DeviceConfigRepo) GetAll(ctx context.Context) ([]domain.DeviceConfig, error) {
	rows, err := r.pool.Query(ctx, deviceConfigSelect+" ORDER BY ep.name, d.name")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []domain.DeviceConfig
	for rows.Next() {
		d, err := scanDeviceConfig(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, d)
	}
	return out, rows.Err()
}

func (r *DeviceConfigRepo) GetByID(ctx context.Context, id string) (*domain.DeviceConfig, error) {
	d, err := scanDeviceConfig(r.pool.QueryRow(ctx, deviceConfigSelect+" WHERE d.id = $1", id))
	if noRows(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &d, nil
}

// Create stores the plaintext key generated by the caller (app layer). In V1
// the schema keeps `devices.api_key` in plaintext with a UNIQUE constraint;
// a collision (astronomically unlikely for a 32-byte random key) surfaces as
// 409 via mapDBError.
func (r *DeviceConfigRepo) Create(ctx context.Context, entryPointID, name, apiKey string) (domain.DeviceConfig, error) {
	var id string
	err := r.pool.QueryRow(ctx,
		`INSERT INTO devices (entry_point_id, name, api_key) VALUES ($1, $2, $3) RETURNING id`,
		entryPointID, name, apiKey).Scan(&id)
	if err != nil {
		return domain.DeviceConfig{}, mapDBError(err, "No se pudo registrar el dispositivo.")
	}
	d, err := r.GetByID(ctx, id)
	if err != nil {
		return domain.DeviceConfig{}, err
	}
	return *d, nil
}

func (r *DeviceConfigRepo) Revoke(ctx context.Context, id string) (bool, error) {
	tag, err := r.pool.Exec(ctx,
		`UPDATE devices SET is_active = FALSE, revoked_at = now()
		 WHERE id = $1 AND revoked_at IS NULL`, id)
	if err != nil {
		return false, mapDBError(err, "No se pudo revocar el dispositivo.")
	}
	return tag.RowsAffected() > 0, nil
}
