[env:esp32]
platform = espressif32
board = esp32
framework = arduino
monitor_speed = 115200

# Libraries
lib_deps =
    https://github.com/elechouse/PN532
    bblanchon/ArduinoJson @ ^6.21.0

# Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
